name: 'Get AKS Kubeconfig'
description: 'sets a kubeconfig secret on the repository'
inputs:
  APP_ID:
    description: 'Client ID for Service Principal'
    required: true
  APP_SECRET:
    description: 'Client Secret for Service Principal'
    required: true
  SUBSCRIPTION_ID:
    description: 'Subscription for Service Principal'
    required: true
  TENANT_ID:
    description: 'Tenant for Service Principal'
    required: true
  RESOURCE_GROUP_NAME: 
    description: 'Resource Group for cluster'
    required: true
  CLUSTER_NAME:
    description: 'Name for cluster'
    required: true
  SECRET_NAME:
    description: 'Secret name for kube-config'
    required: false
    default: 'KUBECONFIG'
runs:
  using: "composite"
  steps:
    - run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      shell: bash
    - run: ${{ github.action_path }}/getKubeConfig.sh
      env:
        APP_ID: ${{ inputs.APP_ID }}
        APP_SECRET: ${{ inputs.APP_SECRET }}
        SUBSCRIPTION_ID: ${{ inputs.SUBSCRIPTION_ID }}
        TENANT_ID: ${{ inputs.TENANT_ID }}
        RESOURCE_GROUP_NAME: ${{ inputs.RESOURCE_GROUP_NAME }}
        CLUSTER_NAME: ${{ inputs.CLUSTER_NAME }}
      shell: bash
    - run: gh secret set ${{ inputs.SECRET_NAME }} < ~/.kube/config
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}